#database
#build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src

COPY ["Customer.Api.Data/Customer.Api.Data.csproj", "Customer.Api.Data/"]
RUN dotnet restore "Customer.Api.Data/Customer.Api.Data.csproj"
COPY ["Customer.Api.Data/", "Customer.Api.Data/"]

COPY ["Customer.Api.Database/Customer.Api.Database.csproj", "Customer.Api.Database/"]
RUN dotnet restore "Customer.Api.Database/Customer.Api.Database.csproj"
COPY ["Customer.Api.Database/", "Customer.Api.Database/"]

RUN dotnet publish "Customer.Api.Database/Customer.Api.Database.csproj" -c Release -o out --no-restore

#serve stage
FROM mcr.microsoft.com/dotnet/runtime:8.0 as base
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Customer.Api.Database.dll"]