
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src
COPY ["PostDeploy", "PostDeploy"]
COPY ["PreDeploy", "PreDeploy"]
COPY ["SqlDatabaseCustomer.sqlproj", ""]

RUN dotnet build

FROM mcr.microsoft.com/mssql/server:2022-latest as db-env
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=P+Lv27vGUH7e
ENV MSSQL_PID="Developer"
ENV MSSQL_AGENT_ENABLED="true"
ENV MSSQL_TCP_PORT=1433

EXPOSE 1433

WORKDIR /db

COPY --from=build-env /src/bin/Debug/SqlDatabaseCustomer.dacpac .

USER root
RUN apt-get update 
RUN apt-get install unzip 
RUN apt-get install libunwind8 

RUN wget -progress=bar:force -q -O sqlpackage.zip https://go.microsoft.com/fwlink/?linkid=2261577
RUN unzip -qq /db/sqlpackage.zip -d /opt/sqlpackage 

RUN chmod +x /opt/sqlpackage/sqlpackage 
RUN chown -R mssql /opt/sqlpackage
RUN mkdir /tmp/db
RUN chown -R mssql /tmp/db

COPY ./entrypoint.sh .

CMD ["sh","entrypoint.sh"]


