#api
#build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src
COPY ["Identity.Api/Identity.Api.csproj", "Identity.Api/"]
COPY ["Identity.Data/Identity.Data.csproj", "Identity.Data/"]


RUN dotnet restore "Identity.Api/Identity.Api.csproj"
COPY . .
RUN dotnet publish "Identity.Api/Identity.Api.csproj" --no-restore -c Release -o /app/publish

#serve stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
COPY --from=build-env /app/publish .

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["dotnet", "Identity.Api.dll"]